 # Use a lightweight Nginx image
FROM nginx:alpine

# Copy the static files from the frontend directory to the Nginx html directory
COPY frontend/ /usr/share/nginx/html

# Expose port 80 for Nginx
EXPOSE 80
